# Generated by Django 5.2.17 on 2026-10-01 19:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Full description of the challenge. Markdown supported.')),
                ('image', models.ImageField(blank=True, help_text='Banner/cover image for the challenge card.', null=True, upload_to='challenges/')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, help_text='When the challenge kicks off.')),
                ('end_time', models.DateTimeField(help_text='Deadline — when the challenge closes. The frontend uses this to auto-shrink the spotlight card.')),
                ('registration_link', models.URLField(blank=True, help_text='External registration / submission link (Devfolio, Unstop, etc.).', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
                'ordering': ['-end_time'],
            },
        ),
    ]
