# Generated by Django 5.2.17 on 2026-10-01 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='duration',
            field=models.CharField(blank=True, help_text='E.g. "60 Min" — displayed as a quick-fact badge.', max_length=50),
        ),
        migrations.AddField(
            model_name='challenge',
            name='judging_type',
            field=models.CharField(blank=True, help_text='E.g. "Live Instant Judging" — displayed as a quick-fact badge.', max_length=100),
        ),
        migrations.AddField(
            model_name='challenge',
            name='long_description',
            field=models.TextField(blank=True, help_text='Rich/detailed description for the challenge detail page. Markdown supported.'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='max_seats',
            field=models.CharField(blank=True, help_text='E.g. "40 Max" — displayed as a quick-fact badge.', max_length=50),
        ),
        migrations.AddField(
            model_name='challenge',
            name='poster_image',
            field=models.ImageField(blank=True, help_text='Hero banner for the challenge detail/spotlight page.', null=True, upload_to='challenges/posters/'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='short_description',
            field=models.TextField(blank=True, help_text='One-line teaser shown on external challenge cards.'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from title. Used in share-link URLs.', max_length=220, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.TextField(help_text='Legacy full description field. Still used as a fallback for the list-card excerpt.'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='image',
            field=models.ImageField(blank=True, help_text='Banner/cover image for the challenge card (list view).', null=True, upload_to='challenges/'),
        ),
        migrations.CreateModel(
            name='ChallengeReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Prize tier label (e.g. "1st Place Champion").', max_length=255)),
                ('prize_value', models.CharField(blank=True, help_text='Monetary / credit value (e.g. "$40 Value"). Optional.', max_length=100)),
                ('description', models.TextField(help_text='What the winner receives. Markdown supported.')),
                ('order', models.IntegerField(default=0, help_text='Display order — lower numbers appear first.')),
                ('challenge', models.ForeignKey(help_text='Parent challenge this reward belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='challenges.challenge')),
            ],
            options={
                'verbose_name': 'Challenge Reward',
                'verbose_name_plural': 'Challenge Rewards',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short heading for the rule (e.g. "Prompt Reveal at Minute 00").', max_length=255)),
                ('description', models.TextField(help_text='Full rule explanation. Markdown supported.')),
                ('order', models.IntegerField(default=0, help_text='Display order — lower numbers appear first.')),
                ('challenge', models.ForeignKey(help_text='Parent challenge this rule belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='challenges.challenge')),
            ],
            options={
                'verbose_name': 'Challenge Rule',
                'verbose_name_plural': 'Challenge Rules',
                'ordering': ['order', 'id'],
            },
        ),
    ]
