# Generated by Django 5.2.17 on 2026-10-01 21:03

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_challenge_duration_challenge_judging_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='long_description',
            field=tinymce.models.HTMLField(blank=True, help_text='Rich HTML content for the challenge detail page. Edited via TinyMCE. Rendered as HTML in the React frontend.'),
        ),
    ]
