# Generated by Django 5.2.17 on 2026-10-02 07:37

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_alter_challenge_long_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Full name of the hackathon.', max_length=255)),
                ('slug', models.SlugField(help_text='URL-safe identifier. Auto-generated from title.', max_length=270, unique=True)),
                ('organizer', models.CharField(help_text='e.g., AWS, Devfolio, MLH, GitHub', max_length=100)),
                ('cover_image', models.ImageField(blank=True, help_text='Banner / card cover image for the hackathon.', null=True, upload_to='hackathons/')),
                ('registration_link', models.URLField(help_text='Official link to register or join the hackathon.', max_length=500)),
                ('start_date', models.DateTimeField(help_text='When the hackathon begins.')),
                ('end_date', models.DateTimeField(help_text='When the hackathon ends / submissions close.')),
                ('total_prize_pool', models.CharField(blank=True, help_text='e.g., "$28,000" or "₹1 Lakh". Leave blank if not disclosed.', max_length=100)),
                ('mode', models.CharField(choices=[('Online', 'Online'), ('In-Person', 'In-Person'), ('Hybrid', 'Hybrid')], default='Online', help_text='Format of the hackathon.', max_length=50)),
                ('short_description', models.TextField(blank=True, help_text='One-line teaser shown on the hackathon card.')),
                ('long_description', tinymce.models.HTMLField(blank=True, help_text='Rich HTML content for the hackathon detail page. Edited via TinyMCE. Rendered with dangerouslySetInnerHTML in React.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hackathon',
                'verbose_name_plural': 'Hackathons',
                'ordering': ['-start_date'],
            },
        ),
    ]
