# Generated by Django 5.2.17 on 2026-10-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_hackathon_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='event_type',
            field=models.CharField(choices=[('sprint', 'Internal Sprint'), ('hackathon', 'Global Hackathon'), ('workshop', 'Workshop / Bootcamp'), ('event', 'Online Event')], default='sprint', help_text='The type of event — drives frontend routing and card styling.', max_length=20),
        ),
        migrations.AddField(
            model_name='challenge',
            name='external_link',
            field=models.URLField(blank=True, help_text='Official hackathon registration page (opens in a new tab on the detail page).', null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='organizer',
            field=models.CharField(blank=True, help_text='Organizer name — e.g. AWS, MLH, GitHub. Leave blank for internal sprints.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='total_prize_pool',
            field=models.CharField(blank=True, help_text='Prize pool value — e.g. "$28,000" or "₹1 Lakh". Leave blank if none.', max_length=100, null=True),
        ),
    ]
