# Generated by Django 5.2.17 on 2026-10-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_add_event_type_and_external_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='poster_image',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='image',
            field=models.ImageField(blank=True, help_text='Cover image for both list-view card and detail hero banner.', null=True, upload_to='challenges/'),
        ),
    ]
