# Generated by Django 5.2.17 on 2026-10-02 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_remove_poster_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('submitted', 'Project Submitted'), ('evaluated', 'Evaluated / Scored')], default='registered', help_text='Current participation stage for this student.', max_length=20)),
                ('project_link', models.URLField(blank=True, help_text='GitHub repo or live project URL submitted by the student.', null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True, help_text='When the student registered for this challenge.')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Timestamp of when the project was submitted.', null=True)),
                ('challenge', models.ForeignKey(help_text='The challenge this registration belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='challenges.challenge')),
                ('student', models.ForeignKey(help_text='The registered student user.', on_delete=django.db.models.deletion.CASCADE, related_name='challenge_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Challenge Registration',
                'verbose_name_plural': 'Challenge Registrations',
                'ordering': ['-registered_at'],
                'unique_together': {('challenge', 'student')},
            },
        ),
    ]
