# Generated by Django 5.2.17 on 2026-10-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_challengeregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengeregistration',
            name='project_link',
        ),
        migrations.AddField(
            model_name='challengeregistration',
            name='proof_link',
            field=models.URLField(blank=True, help_text='Public Google Drive link of the registration screenshot', null=True),
        ),
        migrations.AlterField(
            model_name='challengeregistration',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('pending_approval', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='registered', help_text='Current participation stage for this student.', max_length=20),
        ),
        migrations.AlterField(
            model_name='challengeregistration',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of when the proof screenshot was submitted.', null=True),
        ),
    ]
