# Generated by Django 5.2.17 on 2026-10-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_remove_challengeregistration_project_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='submission_instructions',
            field=models.TextField(blank=True, help_text="Additional submission rules shown to students on their dashboard — e.g. 'Must include #AWSSBG-RIT-2026 in README'.", null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='submission_type',
            field=models.CharField(choices=[('github', 'GitHub Repository URL'), ('drive', 'Google Drive Link (Screenshot/Doc)'), ('live_url', 'Live Project/Website URL')], default='github', help_text='Controls what type of link students must submit and which anti-cheat rules are shown.', max_length=20),
        ),
    ]
