# Generated by Django 5.2.17 on 2026-10-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0009_challenge_submission_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeregistration',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Explanation provided by admins if submission proof is rejected.', null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='submission_type',
            field=models.CharField(choices=[('github', 'GitHub Repository URL'), ('drive', 'Google Drive Link (Screenshot/Doc)'), ('live_url', 'Live Project/Website URL'), ('official', 'Official Platform URL (Devpost/Unstop/Taikai)')], default='github', help_text='Controls what type of link students must submit and which anti-cheat rules are shown.', max_length=20),
        ),
    ]
