# Generated by Django 5.2.17 on 2026-10-03 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0010_challengeregistration_rejection_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeregistration',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who approved this registration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_challenges', to=settings.AUTH_USER_MODEL),
        ),
    ]
