# Generated by Django 5.2.17 on 2026-08-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='mobile',
            field=models.CharField(blank=True, help_text='Mobile / Phone number', max_length=20),
        ),
    ]
