# Generated by Django 5.2.17 on 2026-10-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactmessage_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, help_text='Mark as read after reviewing — hides it from the unread counter in the admin sidebar.'),
        ),
    ]
