# Generated by Django 5.2.17 on 2026-08-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_registration_open',
            field=models.BooleanField(default=True, help_text='Uncheck to close registrations. The Register button will become disabled on the frontend.'),
        ),
    ]
