# Generated by Django 5.2.17 on 2026-09-02 12:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_is_registration_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Set the exact date AND time for the event (e.g. 2026-09-05 10:00). The frontend countdown timer uses this precise timestamp.'),
        ),
    ]
