# Generated by Django 5.2.17 on 2026-09-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from title. Used in shareable deep-link URLs (e.g. /events?event=smart-india-hackathon).', max_length=255, null=True, unique=True),
        ),
    ]
