# Generated by Django 5.2.17 on 2026-09-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Google Meet or Zoom link for the live session', max_length=500, null=True),
        ),
    ]
