# Generated by Django 5.2.17 on 2026-09-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ppt_link',
            field=models.URLField(blank=True, help_text='Google Drive link for the event PPT/Slides', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='recording_link',
            field=models.URLField(blank=True, help_text='YouTube or Instagram link for the event recording', max_length=500, null=True),
        ),
    ]
