# Generated by Django 5.2.17 on 2026-09-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_add_ppt_and_recording_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='recording_link',
        ),
        migrations.AddField(
            model_name='event',
            name='other_material_link',
            field=models.URLField(blank=True, help_text='Google Drive link for PDFs, Zip files, or other resources', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='youtube_link',
            field=models.URLField(blank=True, help_text='YouTube link for the event recording', max_length=500, null=True),
        ),
    ]
