export const CORE_TEAM = [
  {
    id: 1,
    name: 'Aditya Raj',
    role: 'Group Lead',
    tagline: 'Cloud Architecture & DevOps',
    initials: 'AR',
    color: 'from-sbg-purple to-sbg-purple-dark',
    skills: ['AWS', 'Cloud Infra', 'DevOps', 'Python'],
    linkedin: '#',
    github: '#',
    isLead: true,
  },
  {
    id: 2,
    name: 'Rajat Raj Seth',
    role: 'Core Team',
    tagline: 'Full-Stack & Backend Systems',
    initials: 'RS',
    color: 'from-blue-600 to-blue-800',
    skills: ['React', 'Node.js', 'Django', 'PostgreSQL'],
    linkedin: '#',
    github: '#',
    isLead: false,
  },
  {
    id: 3,
    name: 'Aashish',
    role: 'Core Team',
    tagline: 'Machine Learning & AI',
    initials: 'AA',
    color: 'from-emerald-600 to-emerald-800',
    skills: ['ML', 'Python', 'TensorFlow', 'AWS SageMaker'],
    linkedin: '#',
    github: '#',
    isLead: false,
  },
  {
    id: 4,
    name: 'Anshu Priya',
    role: 'Core Team',
    tagline: 'UI/UX & Frontend Engineering',
    initials: 'AP',
    color: 'from-rose-600 to-rose-800',
    skills: ['Figma', 'React', 'Tailwind', 'Design Systems'],
    linkedin: '#',
    github: '#',
    isLead: false,
  },
  {
    id: 5,
    name: 'Ranvijay',
    role: 'Core Team',
    tagline: 'Embedded Systems & IoT',
    initials: 'RV',
    color: 'from-amber-600 to-amber-800',
    skills: ['Embedded C', 'IoT', 'RTOS', 'AWS IoT Core'],
    linkedin: '#',
    github: '#',
    isLead: false,
  },
];
