# Generated by Django 5.2.17 on 2026-08-26 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Subject line of the broadcast email.', max_length=255)),
                ('message', models.TextField(help_text='Body of the broadcast email (plain text).')),
                ('send_to_all_users', models.BooleanField(default=False, help_text="If checked, the email will be sent to ALL registered users. Overrides the 'Specific Users' selection.")),
                ('sent_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this broadcast was saved and dispatched.')),
                ('specific_users', models.ManyToManyField(blank=True, help_text="Select individual users to receive this email. Ignored when 'Send to all users' is enabled.", related_name='email_broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Broadcast',
                'verbose_name_plural': 'Email Broadcasts',
                'ordering': ['-sent_at'],
            },
        ),
    ]
