# Generated by Django 5.2.17 on 2026-10-02 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial_emailbroadcast'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuilderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_points', models.IntegerField(default=0, help_text='Accumulated XP points earned through check-ins and activities.')),
                ('current_streak', models.IntegerField(default=0, help_text='Number of consecutive daily check-in days.')),
                ('longest_streak', models.IntegerField(default=0, help_text='All-time longest consecutive check-in streak.')),
                ('last_checkin_date', models.DateField(blank=True, help_text='Date of the most recent daily check-in.', null=True)),
                ('is_core_team', models.BooleanField(default=False, help_text='Set True for AWS SBG core team members. Disables leaderboard XP tracking for Fair Play — staff cannot dominate the student leaderboard.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='The Django user this profile belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='builder_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Builder Profile',
                'verbose_name_plural': 'Builder Profiles',
                'ordering': ['-xp_points', '-current_streak'],
            },
        ),
    ]
