# Generated by Django 5.2.17 on 2026-08-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryphoto',
            name='image',
            field=models.ImageField(upload_to='gallery/'),
        ),
    ]
