# Generated by Django 5.2.17 on 2026-08-26 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_galleryphoto_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryphoto',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who uploaded this photo. Preserved if user is deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_photos', to=settings.AUTH_USER_MODEL),
        ),
    ]
