# Generated by Django 5.2.17 on 2026-08-31 04:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0004_event_is_registration_open'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('need_members', 'Need Members'), ('need_team', 'Need a Team')], db_index=True, help_text="'need_members': has a team, wants people. 'need_team': solo, wants a team.", max_length=15)),
                ('event_name', models.CharField(help_text='Name of the hackathon/event, or "Other" for a custom project.', max_length=200)),
                ('members_needed', models.IntegerField(default=1, help_text='Remaining open slots. Decremented on each accepted PIN. Auto-hidden at 0.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('target_year', models.CharField(choices=[('1st', '1st Year'), ('2nd', '2nd Year'), ('3rd', '3rd Year'), ('4th', '4th Year'), ('any', 'Any Year')], default='any', help_text='Which academic year the creator is looking for.', max_length=10)),
                ('gender_preference', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('any', 'Any')], default='any', help_text='Preferred gender of new teammates.', max_length=10)),
                ('message', models.TextField(help_text='Detailed requirement description visible on the board.')),
                ('secret_pin', models.CharField(help_text='4-digit numeric PIN. Share only with people you want to accept. NEVER exposed in GET APIs.', max_length=4, validators=[django.core.validators.RegexValidator(message='PIN must be exactly 4 numeric digits (e.g. 4821).', regex='^\\d{4}$')])),
                ('is_approved_by_admin', models.BooleanField(default=False, help_text='Admin must manually approve before the post goes live on the board.')),
                ('is_active', models.BooleanField(default=True, help_text='Set to False automatically when members_needed reaches 0.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(help_text='The user who created this post.', on_delete=django.db.models.deletion.CASCADE, related_name='team_requests', to=settings.AUTH_USER_MODEL)),
                ('event_ref', models.ForeignKey(blank=True, help_text='Link to a registered Event. Null if the user chose "Other".', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_requests', to='events.event')),
            ],
            options={
                'verbose_name': 'Team Request',
                'verbose_name_plural': 'Team Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_process', 'In Process'), ('accepted', 'Accepted'), ('timeout', 'Timed Out')], db_index=True, default='in_process', max_length=12)),
                ('locked_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the 4-hour lock window started.')),
                ('interested_user', models.ForeignKey(help_text='The user who clicked Interested.', on_delete=django.db.models.deletion.CASCADE, related_name='team_interests', to=settings.AUTH_USER_MODEL)),
                ('request_post', models.ForeignKey(help_text='The team request post this interest is for.', on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='teamup.teamrequest')),
            ],
            options={
                'verbose_name': 'Team Interest',
                'verbose_name_plural': 'Team Interests',
                'ordering': ['-locked_at'],
                'unique_together': {('request_post', 'interested_user')},
            },
        ),
    ]
