# Generated by Django 5.2.17 on 2026-08-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamrequest',
            name='is_approved_by_admin',
            field=models.BooleanField(default=True, help_text='Automatically approved on creation. Admins can unapprove/delete if needed.'),
        ),
    ]
