# Generated by Django 5.2.17 on 2026-09-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamup', '0002_alter_teamrequest_is_approved_by_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminterest',
            name='locked_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the 2-hour lock window started.'),
        ),
    ]
