# Generated by Django 5.2.17 on 2026-08-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/')),
                ('skills', models.JSONField(blank=True, default=list)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('is_lead', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (lower = first)')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
