# Generated by Django 5.2.17 on 2026-08-22 03:55

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['priority_order', 'name'], 'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
        migrations.RemoveField(
            model_name='member',
            name='github',
        ),
        migrations.RemoveField(
            model_name='member',
            name='order',
        ),
        migrations.RemoveField(
            model_name='member',
            name='photo',
        ),
        migrations.AddField(
            model_name='member',
            name='badge',
            field=models.CharField(blank=True, help_text='e.g. "⭐ Advisor" or "Group Lead"', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='member',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='member',
            name='priority_order',
            field=models.PositiveSmallIntegerField(default=10, help_text='Display order — lower number = closer to top.'),
        ),
    ]
