# Generated by Django 5.2.17 on 2026-08-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_options_remove_member_github_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='members/'),
        ),
    ]
