# Generated by Django 5.2.17 on 2026-08-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_member_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='category',
            field=models.CharField(choices=[('LEADERSHIP', 'Group Leader & Faculty'), ('FOUNDING', 'Founding Member'), ('CORE', 'Core Member')], default='CORE', help_text='Controls which section this member appears in on the Team page.', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='priority_order',
            field=models.PositiveSmallIntegerField(default=10, help_text='Display order — lower number = closer to top (within each category).'),
        ),
    ]
