# Generated by Django 5.2.17 on 2026-08-28 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_member_category_alter_member_priority_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='portfolio_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
