# Generated by Django 5.2.17 on 2026-08-30 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0004_event_is_registration_open'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=100)),
                ('course', models.CharField(help_text='e.g. B.Tech, BCA, MCA', max_length=50)),
                ('branch', models.CharField(help_text='e.g. Computer Science and Engineering', max_length=120)),
                ('section', models.CharField(max_length=10)),
                ('roll_number', models.CharField(max_length=30)),
                ('mobile_number', models.CharField(max_length=15)),
                ('user', models.OneToOneField(help_text='The Django user (Google SSO account) this profile belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the registration was submitted.')),
                ('event', models.ForeignKey(help_text='The event this registration is for.', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('student', models.ForeignKey(help_text='The student who registered.', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'Event Registration',
                'verbose_name_plural': 'Event Registrations',
                'ordering': ['-registered_at'],
                'unique_together': {('event', 'student')},
            },
        ),
    ]
