# Generated by Django 5.2.17 on 2026-08-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='full_name',
            field=models.CharField(blank=True, help_text="Student's full name for certificates and official records.", max_length=150, null=True),
        ),
    ]
