# Generated by Django 5.2.17 on 2026-08-31 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('1st', '1st Year'), ('2nd', '2nd Year'), ('3rd', '3rd Year'), ('4th', '4th Year')], help_text='Academic year of the student (e.g. 1st, 2nd, 3rd, 4th).', max_length=10, null=True),
        ),
    ]
