# Generated by Django 5.2.17 on 2026-08-31 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_add_academic_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='father_name',
        ),
    ]
